import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Festility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>Festility</h1>
      </main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      {/* <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", flexDirection: "row" }}>
            <div className={styles.flex_item}>1</div>
            <div className={styles.flex_item}>2</div>
            <div className={styles.flex_item}>3</div>
            <div className={styles.flex_item}>4</div>
            <div className={styles.flex_item}>5</div>
            <div className={styles.flex_item}>6</div>
            <div className={styles.flex_item}>7</div>
            <div className={styles.flex_item}>8</div>
            <div className={styles.flex_item}>9</div>
            <div className={styles.flex_item}>10</div>
            <div className={styles.flex_item}>11</div>
            <div className={styles.flex_item}>12</div>
            <div className={styles.flex_item}>13</div>
            <div className={styles.flex_item}>14</div>
            <div className={styles.flex_item}>15</div>
            <div className={styles.flex_item}>16</div>
            <div className={styles.flex_item}>17</div>
            <div className={styles.flex_item}>18</div>
            <div className={styles.flex_item}>19</div>
            <div className={styles.flex_item}>20</div>
            <div className={styles.flex_item}>21</div>
            <div className={styles.flex_item}>22</div>
            <div className={styles.flex_item}>23</div>
            <div className={styles.flex_item}>24</div>
          </div>
          <div style={{ display: "flex", flexDirection: "row" }}>
            <div className={styles.flex_item}>1</div>
            <div className={styles.flex_item}>2</div>
            <div className={styles.flex_item}>3</div>
            <div className={styles.flex_item}>4</div>
            <div className={styles.flex_item}>5</div>
            <div className={styles.flex_item}>6</div>
            <div className={styles.flex_item}>7</div>
            <div className={styles.flex_item}>8</div>
            <div className={styles.flex_item}>9</div>
            <div className={styles.flex_item}>10</div>
            <div className={styles.flex_item}>11</div>
            <div className={styles.flex_item}>12</div>
            <div className={styles.flex_item}>13</div>
            <div className={styles.flex_item}>14</div>
            <div className={styles.flex_item}>15</div>
            <div className={styles.flex_item}>16</div>
            <div className={styles.flex_item}>17</div>
            <div className={styles.flex_item}>18</div>
            <div className={styles.flex_item}>19</div>
            <div className={styles.flex_item}>20</div>
            <div className={styles.flex_item}>21</div>
            <div className={styles.flex_item}>22</div>
            <div className={styles.flex_item}>23</div>
            <div className={styles.flex_item}>24</div>
          </div>
        </div> */}
      <div>
        <div style={{ display: "inline-flex", flexDirection: "row" }}>
          <div
            className={styles.slot}
            // style={{ width: `calc(265px + ${0.5 * 130}px)` }}
          >
            <div className={styles.slot_details}>
              <div>
                <span>11:11 – 12:12</span>
              </div>
              <div>
                <span>
                  <strong>
                    Title of this movie which keeps going on and on..
                  </strong>
                </span>
              </div>
              <div>
                <span className={styles.slot__director}>
                  Apichatpong Weerasethakul
                </span>
              </div>
              <div className={styles.slot__duration}>
                <span>130'</span>
              </div>
            </div>
            <div className={styles.slot_actions}>
              <div>
                <span>x2</span>
              </div>
              <div>
                <span>+</span>
              </div>
            </div>
          </div>
          <div className={styles.slot}>
            <div className={styles.slot_details}>
              <div>
                <span>11:11 – 12:12</span>
              </div>
              <div>
                <span>
                  <strong>
                    Title of this movie which keeps going on and on..
                  </strong>
                </span>
              </div>
              <div>
                <span className={styles.slot__director}>
                  Apichatpong Weerasethakul
                </span>
              </div>
              <div className={styles.slot__duration}>
                <span>130'</span>
              </div>
            </div>
            <div className={styles.slot_actions}>
              <span>x2</span>
              <span>+</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
